# Generated by Django 4.2.6 on 2023-10-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('спорт', 'Спорт'), ('Политика', 'Политика'), ('группа 44', 'Группа 44'), ('не важные новости', 'Не Важные Новости')], max_length=100),
        ),
    ]
