# Generated by Django 4.2.6 on 2023-11-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Статьи'},
        ),
    ]
